### ISSUE TITLE
`Auto Cook`: Make my game force close

### ISSUE THREAD

**Issue by WHOIAM121** [Akebi-Private/Akebi-Issue-Tracker#117]

**Comment by yorik100** [comment]
> _No description provided._

Did you enable the option under auto cook? Try disabling it if it's enabled and try normal auto cook again

**Comment by Taiga74164** [comment]
fixed already. make sure you have the updated client

**Comment by yorik100** [comment]
> fixed already. make sure you have the updated client

I can confirm, AutoCook crashes if this option is enabled, was also broken on the free version 1.2.2
![image](https://user-images.githubusercontent.com/16320315/213839691-e4c5ccc5-9027-4d0a-a99d-b18f1c32e3ed.png)

**Comment by Michell-L** [comment]
latest client still crash no matter fast proficiency or normal cook

**Comment by yorik100** [comment]
> latest client still crash no matter fast proficiency or normal cook

Ok I started crashing again with AutoCook on the same update that I wasn't crashing with

**Comment by Taiga74164** [comment]
sorry. next upcoming update today
